config/routes.rb
Rails.application.routes.draw do

  resources :test_users

  resources :models

  mount Spree::Core::Engine, :at => '/'

end

app/models/model.rb
class Model < ActiveRecord::Base
end

app/models/test_user.rb
class TestUser < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    @models = Model.all
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:test_users)
    end
end

app/controllers/test_users_controller.rb
class TestUsersController < ApplicationController
  before_action :set_test_user, only: [:show, :edit, :update, :destroy]

  # GET /test_users
  # GET /test_users.json
  def index
    @test_users = TestUser.all
  end

  # GET /test_users/1
  # GET /test_users/1.json
  def show
  end

  # GET /test_users/new
  def new
    @test_user = TestUser.new
  end

  # GET /test_users/1/edit
  def edit
  end

  # POST /test_users
  # POST /test_users.json
  def create
    @test_user = TestUser.new(test_user_params)

    respond_to do |format|
      if @test_user.save
        format.html { redirect_to @test_user, notice: 'Test user was successfully created.' }
        format.json { render :show, status: :created, location: @test_user }
      else
        format.html { render :new }
        format.json { render json: @test_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_users/1
  # PATCH/PUT /test_users/1.json
  def update
    respond_to do |format|
      if @test_user.update(test_user_params)
        format.html { redirect_to @test_user, notice: 'Test user was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_user }
      else
        format.html { render :edit }
        format.json { render json: @test_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_users/1
  # DELETE /test_users/1.json
  def destroy
    @test_user.destroy
    respond_to do |format|
      format.html { redirect_to test_users_url, notice: 'Test user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_user
      @test_user = TestUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_user_params
      params[:test_user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/test_users_helper.rb
module TestUsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/models/_form.html.erb
<%= form_for(@model) do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>df
  <% end %>

  <div class="field">
    <%= f.label :test_users %><br>
    <%= f.text_field :test_users %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/models/edit.html.erb
<h1>Editing model</h1>

<%= render 'form' %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back', models_path %>

app/views/models/index.html.erb
<h1>Listing models</h1>

<table>
  <thead>
    <tr>
      <th>Test users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @models.each do |model| %>
      <tr>
        <td><%= model.test_users %></td>
        <td><%= link_to 'Show', model %></td>
        <td><%= link_to 'Edit', edit_model_path(model) %></td>
        <td><%= link_to 'Destroy', model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model', new_model_path %>

app/views/models/new.html.erb
<h1>New model</h1>

<%= render 'form' %>

<%= link_to 'Back', models_path %>

app/views/models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Test users:</strong>
  <%= @model.test_users %>
</p>

<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Back', models_path %>

app/views/test_users/_form.html.erb
<%= form_for(@test_user) do |f| %>
  <% if @test_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_user.errors.count, "error") %> prohibited this test_user from being saved:</h2>

      <ul>
      <% @test_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_users/edit.html.erb
<h1>Editing test_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_user %> |
<%= link_to 'Back', test_users_path %>

app/views/test_users/index.html.erb
<h1>Listing test_users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_users.each do |test_user| %>
      <tr>
        <td><%= link_to 'Show', test_user %></td>
        <td><%= link_to 'Edit', edit_test_user_path(test_user) %></td>
        <td><%= link_to 'Destroy', test_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test user', new_test_user_path %>

app/views/test_users/new.html.erb
<h1>New test_user</h1>

<%= render 'form' %>

<%= link_to 'Back', test_users_path %>

app/views/test_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_test_user_path(@test_user) %> |
<%= link_to 'Back', test_users_path %>